# Generated by Django 2.0.1 on 2018-02-02 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('names', '0002_auto_20180202_2319'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='name',
            new_name='names',
        ),
        migrations.RenameModel(
            old_name='post',
            new_name='posts',
        ),
    ]
